In [64]:
import pandas as pd
import numpy as np

In [65]:
def make_float(x):
    if " " in x:    #뛰어쓰기가 있는 경우에는 두 개로 쪼개서 계산 ex) 1123 1/3
        number1, number2 = x.split(" ")
        number2_1, number2_2 = number2.split("/")
        number2 = int(number2_1) / int(number2_2)
        number = int(number1) + number2
    else:
        if "/" in x: #뛰어쓰기가 없지만 /가 있는경우 ex) 1/3
            number1, number2 = x.split("/")
            number = int(number1) / int(number2)
        else: #숫자만 있을때 ex 112
            number = int(x)
    return number

In [54]:
doosan_pb_df = pd.read_csv("basic/doosan_pb_15.csv")
hanhwa_pb_df = pd.read_csv("basic/hanhwa_pb_15.csv")
KIA_pb_df = pd.read_csv("basic/KIA_pb_15.csv")
KT_pb_df = pd.read_csv("basic/KT_pb_15.csv")
LG_pb_df = pd.read_csv("basic/LG_pb_15.csv")
lotte_pb_df = pd.read_csv("basic/lotte_pb_15.csv")
NC_pb_df = pd.read_csv("basic/NC_pb_15.csv")
nexen_pb_df = pd.read_csv("basic/nexen_pb_15.csv")
samsung_pb_df = pd.read_csv("basic/samsung_pb_15.csv")
SK_pb_df = pd.read_csv("basic/SK_pb_15.csv")

In [55]:
doosan_pd_df = pd.read_csv("detail/doosan_pd_15.csv")
hanhwa_pd_df = pd.read_csv("detail/hanhwa_pd_15.csv")
KIA_pd_df = pd.read_csv("detail/KIA_pd_15.csv")
KT_pd_df = pd.read_csv("detail/KT_pd_15.csv")
LG_pd_df = pd.read_csv("detail/LG_pd_15.csv")
lotte_pd_df = pd.read_csv("detail/lotte_pd_15.csv")
NC_pd_df = pd.read_csv("detail/NC_pd_15.csv")
nexen_pd_df = pd.read_csv("detail/nexen_pd_15.csv")
samsung_pd_df = pd.read_csv("detail/samsung_pd_15.csv")
SK_pd_df = pd.read_csv("detail/SK_pd_15.csv")

In [56]:
doosan_d_df = pd.read_csv("../defense/doosan_d.csv")
hanhwa_d_df = pd.read_csv("../defense/hanhwa_d.csv")
KIA_d_df = pd.read_csv("../defense/KIA_d.csv")
KT_d_df = pd.read_csv("../defense/KT_d.csv")
LG_d_df = pd.read_csv("../defense/LG_d.csv")
lotte_d_df = pd.read_csv("../defense/lotte_d.csv")
NC_d_df = pd.read_csv("../defense/NC_d.csv")
nexen_d_df = pd.read_csv("../defense/nexen_d.csv")
samsung_d_df = pd.read_csv("../defense/samsung_d.csv")
SK_d_df = pd.read_csv("../defense/SK_d.csv")

In [57]:
doosan_df = doosan_pb_df.merge(doosan_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]
hanhwa_df = hanhwa_pb_df.merge(hanhwa_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]
KIA_df = KIA_pb_df.merge(KIA_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]
KT_df = KT_pb_df.merge(KT_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]
LG_df = LG_pb_df.merge(LG_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]
lotte_df = lotte_pb_df.merge(lotte_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]
NC_df = NC_pb_df.merge(NC_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]
nexen_df = nexen_pb_df.merge(nexen_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]
samsung_df = samsung_pb_df.merge(samsung_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]
SK_df = SK_pb_df.merge(SK_pd_df, left_on="name",right_on="name")[["name", "team_x", "ERA_x", "G", "W", "L", "SV", "HLD", "WPCT", "IP", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO"]]

In [58]:
doosan_df = doosan_df.rename(columns={"team_x":"team"})
hanhwa_df = hanhwa_df.rename(columns={"team_x":"team"})
KIA_df = KIA_df.rename(columns={"team_x":"team"})
KT_df = KT_df.rename(columns={"team_x":"team"})
LG_df = LG_df.rename(columns={"team_x":"team"})
lotte_df = lotte_df.rename(columns={"team_x":"team"})
NC_df = NC_df.rename(columns={"team_x":"team"})
nexen_df = nexen_df.rename(columns={"team_x":"team"})
samsung_df = samsung_df.rename(columns={"team_x":"team"})
SK_df = SK_df.rename(columns={"team_x":"team"})

In [59]:
doosan_df = doosan_df.rename(columns={"ERA_x":"ERA"})
hanhwa_df = hanhwa_df.rename(columns={"ERA_x":"ERA"})
KIA_df = KIA_df.rename(columns={"ERA_x":"ERA"})
KT_df = KT_df.rename(columns={"ERA_x":"ERA"})
LG_df = LG_df.rename(columns={"ERA_x":"ERA"})
lotte_df = lotte_df.rename(columns={"ERA_x":"ERA"})
NC_df = NC_df.rename(columns={"ERA_x":"ERA"})
nexen_df = nexen_df.rename(columns={"ERA_x":"ERA"})
samsung_df = samsung_df.rename(columns={"ERA_x":"ERA"})
SK_df = SK_df.rename(columns={"ERA_x":"ERA"})

In [60]:
doosan_df = doosan_df.merge(doosan_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
hanhwa_df = hanhwa_df.merge(hanhwa_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
KIA_df = KIA_df.merge(KIA_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
KT_df = KT_df.merge(KT_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
LG_df = LG_df.merge(LG_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
lotte_df = lotte_df.merge(lotte_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
NC_df = NC_df.merge(NC_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
nexen_df = nexen_df.merge(nexen_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
samsung_df = samsung_df.merge(samsung_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
SK_df = SK_df.merge(SK_d_df, left_on="name",right_on="name")[["name", "team", "ERA", "G", "W", "L", "SV", "HLD", "WPCT", "IP_x", "H", "HR", "BB", "HBP", "SO", "R", "ER", "WHIP", "GS_x", "Wgs", "Wgr", "GF", "SVO", "TS", "GDP", "GO", "AO", "GO/AO", "PO", "PKO", "DP", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]

In [61]:
doosan_df = doosan_df.rename(columns={"IP_x":"IP"})
hanhwa_df = hanhwa_df.rename(columns={"IP_x":"IP"})
KIA_df = KIA_df.rename(columns={"IP_x":"IP"})
KT_df = KT_df.rename(columns={"IP_x":"IP"})
LG_df = LG_df.rename(columns={"IP_x":"IP"})
lotte_df = lotte_df.rename(columns={"IP_x":"IP"})
NC_df = NC_df.rename(columns={"IP_x":"IP"})
nexen_df = nexen_df.rename(columns={"IP_x":"IP"})
samsung_df = samsung_df.rename(columns={"IP_x":"IP"})
SK_df = SK_df.rename(columns={"IP_x":"IP"})

In [62]:
doosan_df = doosan_df.rename(columns={"GS_x":"GS"})
hanhwa_df = hanhwa_df.rename(columns={"GS_x":"GS"})
KIA_df = KIA_df.rename(columns={"GS_x":"GS"})
KT_df = KT_df.rename(columns={"GS_x":"GS"})
LG_df = LG_df.rename(columns={"GS_x":"GS"})
lotte_df = lotte_df.rename(columns={"GS_x":"GS"})
NC_df = NC_df.rename(columns={"GS_x":"GS"})
nexen_df = nexen_df.rename(columns={"GS_x":"GS"})
samsung_df = samsung_df.rename(columns={"GS_x":"GS"})
SK_df = SK_df.rename(columns={"GS_x":"GS"})

In [66]:
doosan_df["IP"] = doosan_df["IP"].apply(make_float)
hanhwa_df["IP"] = hanhwa_df["IP"].apply(make_float)
KIA_df["IP"] = KIA_df["IP"].apply(make_float)
KT_df["IP"] = KT_df["IP"].apply(make_float)
LG_df["IP"] = LG_df["IP"].apply(make_float)
lotte_df["IP"] = lotte_df["IP"].apply(make_float)
NC_df["IP"] = NC_df["IP"].apply(make_float)
nexen_df["IP"] = nexen_df["IP"].apply(make_float)
samsung_df["IP"] = samsung_df["IP"].apply(make_float)
SK_df["IP"] = SK_df["IP"].apply(make_float)

In [68]:
doosan_df.to_csv("doosan_pitcher.csv",encoding='utf-8')
hanhwa_df.to_csv("hanhwa_pitcher.csv",encoding='utf-8')
KIA_df.to_csv("KIA_pitcher.csv",encoding='utf-8')
KT_df.to_csv("KT_pitcher.csv",encoding='utf-8')
LG_df.to_csv("LG_pitcher.csv",encoding='utf-8')
lotte_df.to_csv("lotte_pitcher.csv",encoding='utf-8')
NC_df.to_csv("NC_pitcher.csv",encoding='utf-8')
nexen_df.to_csv("nexen_pitcher.csv",encoding='utf-8')
samsung_df.to_csv("samsung_pitcher.csv",encoding='utf-8')
SK_df.to_csv("SK_pitcher.csv",encoding='utf-8')

In [69]:
pitcher_df = pd.concat([doosan_df, hanhwa_df, KIA_df, KT_df, LG_df, lotte_df, NC_df, nexen_df, samsung_df, SK_df]).reset_index(drop=True)

In [70]:
pitcher_df.to_csv("pitcher_final.csv",encoding="utf-8")

In [71]:
pitcher_df

,name,team,ERA,G,W,L,SV,HLD,WPCT,IP,...,PO,PKO,DP,A,SB,CS,PB,E,FPCT,CS%
0,오장훈,두산,0,1,0,0,0,0,-,1.000000,...,0,0,0,0,0,0,0,0,0.000000,0.0
1,김강률,두산,2.45,16,3,1,0,3,0.750,14.666667,...,1,0,0,5,0,0,0,0,1.000000,0.0
2,이현승,두산,2.89,41,3,1,18,2,0.750,46.666667,...,2,0,1,7,0,0,0,1,0.900000,0.0
3,허준혁,두산,3.57,16,3,2,0,0,0.600,63.000000,...,1,0,0,7,0,0,0,0,1.000000,0.0
4,함덕주,두산,3.65,68,7,2,2,16,0.778,61.666667,...,2,0,0,9,0,0,0,0,1.000000,0.0
5,유희관,두산,3.94,30,18,5,0,0,0.783,189.666667,...,10,1,3,38,0,0,0,0,1.000000,0.0
6,윤명준,두산,3.97,60,4,6,6,7,0.400,68.000000,...,3,1,1,9,0,0,0,0,1.000000,0.0
7,장원준,두산,4.08,30,12,12,0,0,0.500,169.666667,...,6,0,2,31,0,0,0,0,1.000000,0.0
8,이현호,두산,4.19,49,6,1,0,2,0.857,86.000000,...,6,0,0,10,0,0,0,2,0.888889,0.0
9,노경은,두산,4.47,47,1,4,4,0,0.200,58.333333,...,5,1,0,8,0,0,0,1,0.928571,0.0
10,니퍼트,두산,5.1,20,6,5,0,0,0.545,90.000000,...,6,0,0,17,0,0,0,1,0.958333,0.0
11,양현,두산,5.23,13,0,0,0,0,-,10.333333,...,0,1,0,1,0,0,0,0,1.000000,0.0
12,스와잭,두산,5.26,20,5,7,0,1,0.417,92.333333,...,3,0,0,12,0,0,0,4,0.789474,0.0
13,오현택,두산,5.3,61,1,3,0,13,0.250,56.000000,...,5,0,0,9,0,0,0,1,0.933333,0.0
14,남경호,두산,6,5,0,0,0,0,-,9.000000,...,0,0,0,0,0,0,0,0,0.000000,0.0
15,이재우,두산,6.26,37,0,2,0,9,0.000,46.000000,...,0,0,0,7,0,0,0,0,1.000000,0.0
16,진야곱,두산,7.01,47,5,9,0,4,0.357,102.666667,...,6,0,1,14,0,0,0,1,0.952381,0.0
17,김명성,두산,7.79,17,1,0,0,0,1.000,17.333333,...,1,0,0,2,0,0,0,0,1.000000,0.0
18,마야,두산,8.17,13,2,5,0,0,0.286,68.333333,...,5,0,1,13,0,0,0,1,0.947368,0.0
19,김수완,두산,8.8,9,0,0,0,0,-,15.333333,...,0,0,1,5,0,0,0,0,1.000000,0.0
20,조승수,두산,9,1,0,0,0,0,-,1.000000,...,0,0,0,0,0,0,0,0,0.000000,0.0
21,변진수,두산,10.8,1,1,0,0,0,1.000,1.666667,...,0,0,0,0,0,0,0,0,0.000000,0.0
22,박종기,두산,11.57,3,0,0,0,0,-,2.333333,...,0,0,0,0,0,0,0,0,0.000000,0.0
23,이원재,두산,12.66,12,1,0,0,0,1.000,10.666667,...,1,0,0,2,0,0,0,0,1.000000,0.0
24,장민익,두산,29.25,4,0,0,0,0,-,4.000000,...,0,0,0,0,0,0,0,0,0.000000,0.0
25,이용호,두산,81,2,0,0,0,0,-,0.333333,...,0,0,0,1,0,0,0,0,1.000000,0.0
26,구본범,한화,0.00,3,0,0,0,0,-,1.000000,...,0,0,0,0,0,0,0,0,0.000000,0.0
27,마일영,한화,0.00,2,0,0,0,0,-,0.333333,...,0,0,0,0,0,0,0,0,0.000000,0.0
28,임경완,한화,-,1,0,0,0,0,-,0.000000,...,0,0,0,0,0,0,0,0,0.000000,0.0
29,조영우,한화,0.00,1,0,0,0,0,-,1.000000,...,0,0,0,0,0,0,0,0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,신용운,삼성,7.01,35,1,1,0,2,0.500,25.666667,...,1,0,0,3,0,0,0,0,1.000000,0.0
215,김기태,삼성,7.06,23,3,0,0,0,1.000,29.333333,...,0,0,0,2,0,0,0,1,0.666667,0.0
216,김현우,삼성,7.3,11,0,0,0,0,-,12.333333,...,0,0,0,1,0,0,0,0,1.000000,0.0
217,권오준,삼성,8.04,30,0,0,0,0,-,28.000000,...,1,0,0,4,0,0,0,1,0.833333,0.0
218,정인욱,삼성,8.28,12,2,2,1,0,0.500,29.333333,...,2,0,0,1,0,0,0,0,1.000000,0.0
219,임현준,삼성,11.37,7,0,0,0,0,-,6.333333,...,1,0,0,2,0,0,0,0,1.000000,0.0
220,장필준,삼성,15.75,2,0,0,0,0,-,4.000000,...,0,0,0,2,0,0,0,0,1.000000,0.0
221,윤석주,SK,0,1,0,0,0,0,-,1.333333,...,0,0,0,1,0,0,0,0,1.000000,0.0
222,윤길현,SK,3.16,70,0,4,13,17,0.000,62.666667,...,1,0,0,4,0,0,0,1,0.833333,0.0
223,정우람,SK,3.21,69,7,5,16,11,0.583,70.000000,...,0,0,0,9,0,0,0,0,1.000000,0.0
224,김광현,SK,3.72,30,14,6,0,1,0.700,176.666667,...,12,1,1,30,0,0,0,2,0.954545,0.0
225,이한진,SK,3.86,3,0,0,0,0,-,4.666667,...,1,0,0,0,0,0,0,0,1.000000,0.0
226,신재웅,SK,4.11,61,0,1,0,9,0.000,50.333333,...,3,1,0,6,0,0,0,1,0.900000,0.0
227,켈리,SK,4.13,30,11,10,0,0,0.524,181.000000,...,14,0,3,41,0,0,0,1,0.982143,0.0
228,박민호,SK,4.28,20,1,1,0,1,0.500,27.333333,...,3,0,1,7,0,0,0,0,1.000000,0.0
229,전유수,SK,4.4,66,3,6,1,5,0.333,77.666667,...,2,1,1,9,0,0,0,0,1.000000,0.0
230,밴와트,SK,4.63,12,5,3,0,0,0.625,56.333333,...,1,0,0,9,0,0,0,0,1.000000,0.0
231,이재영,SK,4.65,26,1,0,0,1,1.000,31.000000,...,2,0,1,4,0,0,0,0,1.000000,0.0
232,백인식,SK,4.79,7,1,2,0,0,0.333,20.666667,...,1,0,0,2,0,0,0,0,1.000000,0.0
233,세든,SK,4.99,14,7,5,0,0,0.583,74.000000,...,1,2,0,12,0,0,0,3,0.812500,0.0
234,박종훈,SK,5.19,33,6,8,0,0,0.429,118.000000,...,16,0,0,9,0,0,0,3,0.892857,0.0
235,박정배,SK,5.33,24,2,2,0,2,0.500,25.333333,...,0,0,0,6,0,0,0,0,1.000000,0.0
236,박희수,SK,5.4,14,0,0,0,2,-,10.000000,...,0,0,0,2,0,0,0,0,1.000000,0.0
237,윤희상,SK,5.88,21,5,9,0,0,0.357,93.333333,...,5,0,0,11,0,0,0,1,0.941176,0.0
238,서진용,SK,5.91,18,0,0,0,0,-,21.333333,...,2,0,0,2,0,0,0,0,1.000000,0.0
239,이창욱,SK,6,2,0,0,0,0,-,3.000000,...,2,0,0,0,0,0,0,0,1.000000,0.0
240,채병용,SK,6.07,33,4,4,0,1,0.500,83.000000,...,5,0,0,7,0,0,0,0,1.000000,0.0
241,고효준,SK,6.18,30,0,3,0,0,0.000,51.000000,...,1,0,0,4,0,0,0,2,0.714286,0.0
242,문광은,SK,6.85,53,1,5,1,11,0.167,64.333333,...,4,0,0,6,0,0,0,0,1.000000,0.0
243,김태훈,SK,27,1,0,0,0,0,-,0.333333,...,0,0,0,0,0,0,0,0,0.000000,0.0