In [63]:
import pandas as pd

In [64]:
doosan_hb_df = pd.read_csv("basic/doosan_hb_15.csv")
hanhwa_hb_df = pd.read_csv("basic/hanhwa_hb_15.csv")
KIA_hb_df = pd.read_csv("basic/KIA_hb_15.csv")
KT_hb_df = pd.read_csv("basic/KT_hb_15.csv")
LG_hb_df = pd.read_csv("basic/LG_hb_15.csv")
lotte_hb_df = pd.read_csv("basic/lotte_hb_15.csv")
NC_hb_df = pd.read_csv("basic/NC_hb_15.csv")
nexen_hb_df = pd.read_csv("basic/nexen_hb_15.csv")
samsung_hb_df = pd.read_csv("basic/samsung_hb_15.csv")
SK_hb_df = pd.read_csv("basic/SK_hb_15.csv")

In [65]:
doosan_hd_df = pd.read_csv("detail/doosan_hd_15.csv")
hanhwa_hd_df = pd.read_csv("detail/hanhwa_hd_15.csv")
KIA_hd_df = pd.read_csv("detail/KIA_hd_15.csv")
KT_hd_df = pd.read_csv("detail/KT_hd_15.csv")
LG_hd_df = pd.read_csv("detail/LG_hd_15.csv")
lotte_hd_df = pd.read_csv("detail/lotte_hd_15.csv")
NC_hd_df = pd.read_csv("detail/NC_hd_15.csv")
nexen_hd_df = pd.read_csv("detail/nexen_hd_15.csv")
samsung_hd_df = pd.read_csv("detail/samsung_hd_15.csv")
SK_hd_df = pd.read_csv("detail/SK_hd_15.csv")

In [66]:
doosan_d_df = pd.read_csv("../defense/doosan_d.csv")
hanhwa_d_df = pd.read_csv("../defense/hanhwa_d.csv")
KIA_d_df = pd.read_csv("../defense/KIA_d.csv")
KT_d_df = pd.read_csv("../defense/KT_d.csv")
LG_d_df = pd.read_csv("../defense/LG_d.csv")
lotte_d_df = pd.read_csv("../defense/lotte_d.csv")
NC_d_df = pd.read_csv("../defense/NC_d.csv")
nexen_d_df = pd.read_csv("../defense/nexen_d.csv")
samsung_d_df = pd.read_csv("../defense/samsung_d.csv")
SK_d_df = pd.read_csv("../defense/SK_d.csv")

In [67]:
doosan_r_df = pd.read_csv("../running/doosan_r.csv")
hanhwa_r_df = pd.read_csv("../running/hanhwa_r.csv")
KIA_r_df = pd.read_csv("../running/KIA_r.csv")
KT_r_df = pd.read_csv("../running/KT_r.csv")
LG_r_df = pd.read_csv("../running/LG_r.csv")
lotte_r_df = pd.read_csv("../running/lotte_r.csv")
NC_r_df = pd.read_csv("../running/NC_r.csv")
nexen_r_df = pd.read_csv("../running/nexen_r.csv")
samsung_r_df = pd.read_csv("../running/samsung_r.csv")
SK_r_df = pd.read_csv("../running/SK_r.csv")

In [68]:
doosan_df = doosan_hb_df.merge(doosan_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]
hanhwa_df = hanhwa_hb_df.merge(hanhwa_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]
KIA_df = KIA_hb_df.merge(KIA_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]
KT_df = KT_hb_df.merge(KT_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]
LG_df = LG_hb_df.merge(LG_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]
lotte_df = lotte_hb_df.merge(lotte_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]
NC_df = NC_hb_df.merge(NC_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]
nexen_df = nexen_hb_df.merge(nexen_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]
samsung_df = samsung_hb_df.merge(samsung_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]
SK_df = SK_hb_df.merge(SK_hd_df, left_on="name",right_on="name")[["name", "team_x", "AVG_x", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA"]]

In [69]:
doosan_df = doosan_df.rename(columns={"team_x":"team"})
hanhwa_df = hanhwa_df.rename(columns={"team_x":"team"})
KIA_df = KIA_df.rename(columns={"team_x":"team"})
KT_df = KT_df.rename(columns={"team_x":"team"})
LG_df = LG_df.rename(columns={"team_x":"team"})
lotte_df = lotte_df.rename(columns={"team_x":"team"})
NC_df = NC_df.rename(columns={"team_x":"team"})
nexen_df = nexen_df.rename(columns={"team_x":"team"})
samsung_df = samsung_df.rename(columns={"team_x":"team"})
SK_df = SK_df.rename(columns={"team_x":"team"})

In [70]:
doosan_df = doosan_df.rename(columns={"AVG_x":"AVG"})
hanhwa_df = hanhwa_df.rename(columns={"AVG_x":"AVG"})
KIA_df = KIA_df.rename(columns={"AVG_x":"AVG"})
KT_df = KT_df.rename(columns={"AVG_x":"AVG"})
LG_df = LG_df.rename(columns={"AVG_x":"AVG"})
lotte_df = lotte_df.rename(columns={"AVG_x":"AVG"})
NC_df = NC_df.rename(columns={"AVG_x":"AVG"})
nexen_df = nexen_df.rename(columns={"AVG_x":"AVG"})
samsung_df = samsung_df.rename(columns={"AVG_x":"AVG"})
SK_df = SK_df.rename(columns={"AVG_x":"AVG"})

In [71]:
doosan_df = doosan_df.merge(doosan_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
hanhwa_df = hanhwa_df.merge(hanhwa_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
KIA_df = KIA_df.merge(KIA_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
KT_df = KT_df.merge(KT_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
LG_df = LG_df.merge(LG_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
lotte_df = lotte_df.merge(lotte_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
NC_df = NC_df.merge(NC_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
nexen_df = nexen_df.merge(nexen_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
samsung_df = samsung_df.merge(samsung_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]
SK_df = SK_df.merge(SK_d_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%"]]

In [72]:
doosan_df = doosan_df.merge(doosan_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]
hanhwa_df = hanhwa_df.merge(hanhwa_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]
KIA_df = KIA_df.merge(KIA_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]
KT_df = KT_df.merge(KT_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]
LG_df = LG_df.merge(LG_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]
lotte_df = lotte_df.merge(lotte_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]
NC_df = NC_df.merge(NC_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]
nexen_df = nexen_df.merge(nexen_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]
samsung_df = samsung_df.merge(samsung_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]
SK_df = SK_df.merge(SK_r_df, left_on="name",right_on="name")[["name", "team", "AVG", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "TB", "RBI", "SAC", "SF", "XBH", "GO", "AO", "GO/AO", "GW_RBI", "BB/K", "P/PA", "ISOP", "XR", "GPA", "PO", "PKO", "IP", "DP", "GS", "A", "SB", "CS", "PB", "E", "FPCT", "CS%","SBA", "SB%", "OOB"]]

In [73]:
doosan_df.to_csv("doosan_hitter.csv",encoding='utf-8')
hanhwa_df.to_csv("hanhwa_hitter.csv",encoding='utf-8')
KIA_df.to_csv("KIA_hitter.csv",encoding='utf-8')
KT_df.to_csv("KT_hitter.csv",encoding='utf-8')
LG_df.to_csv("LG_hitter.csv",encoding='utf-8')
lotte_df.to_csv("lotte_hitter.csv",encoding='utf-8')
NC_df.to_csv("NC_hitter.csv",encoding='utf-8')
nexen_df.to_csv("nexen_hitter.csv",encoding='utf-8')
samsung_df.to_csv("samsung_hitter.csv",encoding='utf-8')
SK_df.to_csv("SK_hitter.csv",encoding='utf-8')

In [74]:
hitter_df = pd.concat([doosan_df, hanhwa_df, KIA_df, KT_df, LG_df, lotte_df, NC_df, nexen_df, samsung_df, SK_df]).reset_index(drop=True)

In [75]:
hitter_df.to_csv("hitter_final.csv",encoding='utf-8')

In [76]:
hitter_df

,name,team,AVG,G,PA,AB,R,H,2B,3B,...,A,SB,CS,PB,E,FPCT,CS%,SBA,SB%,OOB
0,박건우,두산,0.342,70,175,158,31,54,12,0,...,2,0,0,0,2,0.973684,0.000000,3,66.666667,2
1,김응민,두산,0.333,4,3,3,1,1,0,0,...,0,0,0,0,0,1.000000,0.000000,0,0.000000,0
2,고영민,두산,0.328,41,77,67,13,22,1,0,...,25,0,0,0,4,0.965517,0.000000,6,66.666667,1
3,김현수,두산,0.326,141,630,512,103,167,26,0,...,13,0,0,0,1,0.997531,0.000000,16,68.750000,7
4,양의지,두산,0.326,132,513,442,70,144,27,0,...,76,93,33,4,6,0.993631,26.190476,9,55.555556,11
5,허경민,두산,0.317,117,453,404,64,128,20,2,...,246,0,0,0,13,0.963585,0.000000,11,72.727273,2
6,김재호,두산,0.307,133,488,410,63,126,24,3,...,352,0,0,0,16,0.971171,0.000000,9,77.777778,4
7,민병헌,두산,0.303,129,561,491,80,149,20,2,...,4,0,0,0,4,0.982979,0.000000,10,70.000000,4
8,정수빈,두산,0.295,128,570,491,79,145,27,7,...,4,0,0,0,2,0.992337,0.000000,24,62.500000,5
9,오재일,두산,0.289,66,213,180,33,52,11,1,...,27,0,0,0,3,0.993684,0.000000,0,0.000000,0
10,최주환,두산,0.282,100,270,238,34,67,16,2,...,125,0,0,0,8,0.963134,0.000000,3,0.000000,3
11,오재원,두산,0.280,120,474,411,60,115,20,2,...,278,0,0,0,8,0.984762,0.000000,39,79.487179,3
12,유민상,두산,0.263,15,45,38,5,10,1,0,...,0,0,0,0,0,1.000000,0.000000,1,100.000000,1
13,로메로,두산,0.253,76,305,265,30,67,16,0,...,60,0,0,0,8,0.974843,0.000000,2,100.000000,6
14,김재환,두산,0.235,48,180,153,24,36,8,0,...,16,0,0,0,2,0.992157,0.000000,5,80.000000,1
15,정진호,두산,0.234,77,172,154,37,36,5,3,...,4,0,0,0,1,0.983051,0.000000,9,66.666667,1
16,국해성,두산,0.200,11,26,20,6,4,1,0,...,3,0,0,0,0,1.000000,0.000000,0,0.000000,0
17,류지혁,두산,0.200,14,5,5,3,1,0,0,...,8,0,0,0,0,1.000000,0.000000,0,0.000000,0
18,장민석,두산,0.189,53,63,53,15,10,2,0,...,1,0,0,0,0,1.000000,0.000000,1,0.000000,1
19,김진형,두산,0.167,14,21,18,3,3,2,0,...,7,0,0,0,0,1.000000,0.000000,0,0.000000,0
20,최재훈,두산,0.152,71,114,99,6,15,3,0,...,19,16,8,2,1,0.996032,33.333333,0,0.000000,1
21,양종민,두산,0.125,32,18,16,6,2,0,0,...,14,0,0,0,1,0.954545,0.000000,1,0.000000,1
22,루츠,두산,0.111,8,30,27,2,3,0,0,...,7,0,0,0,1,0.954545,0.000000,0,0.000000,0
23,노경은,두산,-,1,0,0,0,0,0,0,...,8,0,0,0,1,0.928571,0.000000,0,0.000000,0
24,니퍼트,두산,-,1,0,0,0,0,0,0,...,17,0,0,0,1,0.958333,0.000000,0,0.000000,0
25,양현,두산,-,1,0,0,0,0,0,0,...,1,0,0,0,0,1.000000,0.000000,0,0.000000,0
26,이원재,두산,-,1,0,0,0,0,0,0,...,2,0,0,0,0,1.000000,0.000000,0,0.000000,0
27,이현승,두산,-,2,0,0,0,0,0,0,...,7,0,0,0,1,0.900000,0.000000,0,0.000000,0
28,진야곱,두산,-,2,0,0,0,0,0,0,...,14,0,0,0,1,0.952381,0.000000,0,0.000000,0
29,이창열,한화,0.5,5,2,2,0,1,1,0,...,3,0,0,0,0,1.000000,0.000000,0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,이진석,SK,0.500,6,2,2,1,1,0,0,...,0,0,0,0,0,0.000000,0.000000,1,0.000000,0
242,김기현,SK,0.429,9,9,7,0,3,0,0,...,0,0,0,0,0,1.000000,0.000000,0,0.000000,0
243,이현석,SK,0.333,3,3,3,1,1,0,0,...,0,0,0,0,0,1.000000,0.000000,0,0.000000,0
244,홍명찬,SK,0.333,5,3,3,0,1,0,0,...,0,0,0,0,0,1.000000,0.000000,0,0.000000,0
245,정의윤,SK,0.320,91,297,259,38,83,14,0,...,3,0,0,0,1,0.982143,0.000000,5,100.000000,5
246,이명기,SK,0.315,137,582,521,88,164,30,2,...,1,0,0,0,2,0.989189,0.000000,32,68.750000,6
247,최정민,SK,0.308,8,15,13,1,4,0,0,...,19,0,0,0,0,1.000000,0.000000,0,0.000000,0
248,김성현,SK,0.297,129,449,397,49,118,20,0,...,328,0,0,0,23,0.955684,0.000000,5,20.000000,5
249,최정,SK,0.295,81,330,275,43,81,17,0,...,133,0,0,0,4,0.977778,0.000000,7,71.428571,1
250,허웅,SK,0.294,18,19,17,2,5,1,0,...,3,1,0,0,0,1.000000,0.000000,0,0.000000,0
251,이재원,SK,0.282,140,559,489,58,138,18,1,...,37,42,18,5,3,0.994444,30.000000,4,25.000000,5
252,박정권,SK,0.281,124,494,438,66,123,23,0,...,78,0,0,0,8,0.991862,0.000000,6,50.000000,5
253,나주환,SK,0.268,96,273,246,31,66,15,0,...,186,0,0,0,7,0.979042,0.000000,8,37.500000,3
254,김연훈,SK,0.267,49,73,60,4,16,1,0,...,63,0,0,0,4,0.963303,0.000000,1,0.000000,2
255,이대수,SK,0.264,36,86,72,9,19,3,0,...,48,0,0,0,2,0.967742,0.000000,1,0.000000,0
256,조동화,SK,0.261,119,304,245,38,64,6,1,...,6,0,0,0,1,0.991803,0.000000,21,85.714286,1
257,브라운,SK,0.261,137,539,464,82,121,21,2,...,35,0,0,0,3,0.991453,0.000000,7,71.428571,8
258,정상호,SK,0.254,113,324,279,34,71,11,1,...,46,64,29,1,7,0.988942,31.182796,3,33.333333,5
259,박진만,SK,0.248,78,162,133,12,33,5,0,...,75,0,0,0,2,0.987730,0.000000,2,0.000000,3
260,박재상,SK,0.248,108,292,250,34,62,12,2,...,3,0,0,0,2,0.982759,0.000000,9,44.444444,5
261,김강민,SK,0.246,96,328,293,43,72,17,0,...,6,0,0,0,1,0.994819,0.000000,11,63.636364,2
262,윤중환,SK,0.240,15,28,25,1,6,0,0,...,0,0,0,0,0,1.000000,0.000000,1,0.000000,0
263,박계현,SK,0.231,97,302,264,27,61,2,0,...,188,0,0,0,10,0.968652,0.000000,18,55.555556,2
264,김민식,SK,0.167,23,26,24,4,4,0,0,...,1,1,0,0,0,1.000000,0.000000,0,0.000000,0
265,박윤,SK,0.111,17,29,27,1,3,0,0,...,8,0,0,0,1,0.987013,0.000000,0,0.000000,0
266,김재현,SK,0.105,46,20,19,13,2,0,1,...,0,0,0,0,1,0.888889,0.000000,8,87.500000,1
267,안정광,SK,0.105,10,19,19,0,2,0,0,...,9,0,0,0,1,0.916667,0.000000,0,0.000000,0
268,유서준,SK,0.083,17,13,12,5,1,0,0,...,9,0,0,0,0,1.000000,0.000000,4,75.000000,0
269,고효준,SK,-,1,0,0,0,0,0,0,...,4,0,0,0,2,0.714286,0.000000,0,0.000000,0
270,박정배,SK,-,1,0,0,0,0,0,0,...,6,0,0,0,0,1.000000,0.000000,0,0.000000,0